scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.0
        max_y: 0.0
        max_z: 0.5
        min_x: -0.2
        min_y: -0.2
        min_z: -0.5
        invert: false #sets either the points inside or outside the defined box to be NaN